os: linux
dist: xenial
sudo: required
language: python

services:
- postgresql
- redis-server

addons:
  postgresql: '11.2'

python:
- '3.7'

before_install:
# lots of faff to get pg 11 working
- sudo apt-get update
- sudo apt-get --yes remove postgresql\* > /dev/null
- sudo apt-get install -y postgresql-11 postgresql-client-11
- sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
- sudo service postgresql restart 11
- psql --version
- psql -c 'create role travis superuser login createdb' -U postgres

- nvm install 10.16.3
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
- curl -Lf https://github.com/samuelcolvin/donkey-make/releases/download/v0.3/donk > ./donk
- chmod +x ./donk

cache:
  pip: true
  yarn: true
  directories:
  - node_modules
  - docker_images

install:
- ls -lha docker_images
- ls docker_images/*.tar | xargs -i sh -c "docker load -i {}"
- docker images -a
- ./donk install
- cd js && yarn && yarn list && cd ..

script:
- ./donk lint
- ./donk test
- bash <(curl -s https://codecov.io/bash)
- ./donk build

before_cache:
- docker images -a
- rm docker_images/* || true
- docker save -o docker_images/images.tar $(docker images -a -q)
