language: python

addons:
  postgresql: '9.6'

services:
- postgresql
- redis-server

python:
- '3.7'

dist: xenial
sudo: required

before_install:
- nvm install 10.15.3
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH="$HOME/.yarn/bin:$PATH"

cache:
  pip: true
  yarn: true
  directories:
  - node_modules

install:
- make install
- cd js && yarn && cd ..

script:
- make lint
- make test && bash <(curl -s https://codecov.io/bash)
- ls -lha
