version: 2.1
jobs:
  build:
    machine:
      # CircleCI removed docker layer caching from their free tier even for open projects, how sad :-)
      docker_layer_caching: false
    steps:
      - checkout
      - run: docker version
      - run: |
          curl -Lf https://github.com/samuelcolvin/donkey-make/releases/download/v0.3/donk > ./donk
          chmod +x ./donk
      - run: ./donk build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
