version: 2.1
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker version
      - run: |
          curl -Lf https://github.com/samuelcolvin/donkey-make/releases/download/v0.2/donk > ./donk
          chmod +x ./donk
      - run: ./donk build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
