version: 2.1
jobs:
  build-docker-image:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          set -ex
          pwd
          ls -la
          make build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-docker-image
