[Settings]

[build]
  base = "js/"
  publish = "js/build/"
  command = "./build.py"

[build.environment]
  NODE_VERSION = "10.15.3"
  YARN_VERSION = "1.13.0"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "{main_csp}"

[[headers]]
  for = "/auth-iframes/*"
  [headers.values]
    Content-Security-Policy = "{auth_iframe_csp}"
