[Settings]

[build]
  base = "js/"
  publish = "js/build/"
  command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"

[[headers]]
  for = "iframes/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
