# ===============================================
# pre-built python build stage
FROM em2-python-build as python-build

# ===============================================
# final image
FROM python:3.7-alpine3.8

COPY --from=python-build /usr/local/bin/atoolbox /usr/local/bin/
COPY --from=python-build /lib/* /lib/
COPY --from=python-build /usr/lib/* /usr/lib/
COPY --from=python-build /usr/local/lib/python3.7/site-packages /usr/local/lib/python3.7/site-packages

ENV PYTHONUNBUFFERED 1
ENV APP_ON_DOCKER 1
ENV ATOOLBOX_SETTINGS em2.settings.Settings
WORKDIR /home/root/

# could exclude some files, but would it actually save any space in the image?
ADD ./ /home/root/em2/
ARG COMMIT
ENV COMMIT $COMMIT
ARG BUILD_TIME
ENV BUILD_TIME $BUILD_TIME

CMD ["atoolbox", "web"]
